### ISSUE TITLE
Inconsistent typehints for Reader

### ISSUE THREAD

**Issue by scaytrase** [cebe/php-openapi#23]
https://github.com/cebe/php-openapi/blob/5e68074e2b82a0c0703753eeac3662a8a39e1c5d/src/Reader.php#L30

all reader method declare returning `SpecObjectInterface` while phpdocs say that it should be the `OpenApi` object instance. Also phpdocs are redundand, since `SpecObjectInterface|OpenApi` equals to `SpecObjectInterface` as `OpenApi` implements `SpecObjectInterface`.

It looks like having `OpenApi` as return typehint signature is more straightforward, as it would agree with return phpdoc and comment and the expectations of end user

**Comment by cebe** [comment]
The type of the returned object depends on the value of `$baseType` argument, which defaults to `OpenApi`, but it can be any instance of `SpecObjectInterface`. So the correct annotation would be just `SpecObjectInterface`, I added `OpenApi` because it is the most common type returned and will allow IDEs to provide better autocompletion.

**Comment by cebe** [comment]
I added an additional sentence to the PHPdoc, is it better now?

**Comment by scaytrase** [comment]
It's a bit more clear now, yes. I got the idea, thank you

I hope one day we can create `Reader<OpenApi>::fromJson($json): OpenApi
